default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/todo-list-ex1-development.sqlite3

test:
  <<: *default
  database: db/todo-list-ex1-test.sqlite3

production:
  <<: *default
  database: db/todo-list-ex1-production.sqlite3
